/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PropertyCompany.tenant;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VisitRequest;
import Util.Map;
import Util.MapJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class viewAppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewAppointmentJPanel
     */
    JPanel userProcessContainer;
    UserAccount ua;
    EcoSystem ecosystem;
    VisitRequest request;
    Map maojframe;
    public viewAppointmentJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business,VisitRequest request) throws URISyntaxException, IOException {
         initComponents();
         this.ecosystem=business;
         this.ua = account;
         this. userProcessContainer = userProcessContainer;
         this. request = request;
         maojframe=new Map(userProcessContainer, request.getBuilding());
         maojframe.setVisible(false);
         updatemessage();
    }
    public void updatemessage(){
        try {
            if (request.getAgent().equals(ua)) {
                agentjLabel.setText(request.getCustomer().toString());
            }else
                agentjLabel.setText(request.getAgent().toString());
            
            aptjLabel.setText(request.getBuilding().getAddress());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
            String megString="";
            for(String meg : request.getMessage()){
                megString+=meg+"\n";
                jTextArea1.setText(megString);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        agentjLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aptjLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jButton2.setText("Reply");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(260, 290, 90, 50);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Chat with: ");
        add(jLabel3);
        jLabel3.setBounds(140, 50, 70, 20);

        agentjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        agentjLabel.setText("<value>");
        add(agentjLabel);
        agentjLabel.setBounds(220, 50, 140, 21);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Appartment: ");
        add(jLabel5);
        jLabel5.setBounds(380, 50, 90, 21);

        aptjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        aptjLabel.setText("<value>");
        add(aptjLabel);
        aptjLabel.setBounds(470, 50, 380, 21);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2);
        jScrollPane2.setBounds(19, 78, 880, 190);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Conversation");
        add(jLabel2);
        jLabel2.setBounds(340, 10, 170, 27);

        jTextField1.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jTextField1.setText("Please imput message");
        add(jTextField1);
        jTextField1.setBounds(370, 290, 221, 53);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-map-100.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(650, 280, 110, 90);

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back-arrow.png"))); // NOI18N
        backJButton.setBorderPainted(false);
        backJButton.setContentAreaFilled(false);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(80, 290, 70, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(5, -4, 900, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        mgnaptJPanel jpanel = (mgnaptJPanel) component;
        jpanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
            String meg =new Date().toString()+"\n";
            meg =meg+ua.getUsername()+": ";
            meg=meg+jTextField1.getText()+"";
            System.out.println(meg);
            request.addMessage(meg);
        
        updatemessage();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//        userProcessContainer.add(new MapJPanel(userProcessContainer,request.getBuilding()));
//        layout.next(userProcessContainer);
            maojframe.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agentjLabel;
    private javax.swing.JLabel aptjLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
