/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PropertyCompany.tenant;

import Business.EcoSystem;
import Business.Employee.Leasing;
import Business.Employee.Propority;
import Business.Enterprise.Enterprise;
import Business.Enterprise.RealEstateEnterprise;
import Business.Organization.LeasingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SignLeaseRequest;
import Business.WorkQueue.VisitRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class contractJPanel extends javax.swing.JPanel {

    /**
     * Creates new form contractJPanel
     */
     JPanel userProcessContainer;
    UserAccount ua;
    EcoSystem ecosystem;
    Enterprise enterprise ;
   
    public contractJPanel(JPanel userProcessContainer, UserAccount account,  EcoSystem business, Enterprise enterprise) {
         initComponents();
         this.ecosystem=business;
         this.ua = account;
         this. userProcessContainer = userProcessContainer;
         this.enterprise = enterprise ;
         populateTable( );
    }
 public void populateTable( ) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        if(ua.getWorkQueue().getVisitRequestList()==null){
            return;
        }
        for (VisitRequest wq : ua.getWorkQueue().getVisitRequestList()) {
            Object[] row = new Object[jTable1.getColumnCount()];
            if (wq.getStatus().equals("Intentional")) {
                row[0] = wq;
                row[1] = wq.getAgent();
                row[2] = wq.getBuilding();
                row[3] = wq.getPointedDate();
                row[4] = wq.getStatus();
                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("View contract");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setLayout(null);

        jLabel1.setText("Contracts");
        add(jLabel1);
        jLabel1.setBounds(349, 28, 61, 16);

        jButton2.setText("Sign a contract");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(252, 282, 247, 91);

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(76, 23, 97, 29);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer", "Agent", "Apartment", "RequestDate", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(89, 81, 716, 161);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(5, -4, 930, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
//        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
//        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int row = jTable1.getSelectedRow();
        if (row < 0) {
             JOptionPane.showMessageDialog(null, "Select your contract", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Propority apt = (Propority) jTable1.getValueAt(row, 2) ;
        UserAccount agent = (UserAccount)jTable1.getValueAt(row, 1);
        
        /* Choose Apt
        Propority apt = new Propority() ;
        apt.setAddress("123");
        apt.setAptNo("123");
        apt.setCity("Boston");
        apt.setMonthlyrent(1400);
        apt.setNickname("Lightview1220");
        apt.setProporityNum(1500);
        apt.setSellingprice(800000);
        apt.setSquareFeet(760);
        apt.setState("MA");
        apt.setZipCode("02120");
        */
        
        // Choose Leasing !FIX: need to have EnterpriseName & NetworkName
        RealEstateEnterprise ent =  
                (RealEstateEnterprise) this.ecosystem.findNetwork(apt.getEnterprise().getNetworkName()).getEnterpriseDirectory().findenterprise(apt.getEnterprise().getName());
        ArrayList<Leasing>  leasingList = new ArrayList() ;
        ArrayList<UserAccount>  leasingAccountList = new ArrayList() ;
        for(Organization org:ent.getOrganizationDirectory().getOrganizationList()){
            if (org instanceof LeasingOrganization) {
                for(UserAccount ua : org.getUserAccountDirectory().getUserAccountList())
                    leasingAccountList.add(ua);
                for(Leasing ls : org.getLeasingDirectory().getLeasingList())
                    leasingList.add(ls);
            }
        }
        
        // Assign Leasing 
        // Here I  pick the first leasing in the Enterprise
        for( UserAccount ls : leasingAccountList ){
            System.out.println(ls.getLeasing().getName());
        }
        UserAccount leasingAccount = leasingAccountList.get(0) ;
        
        SignLeaseRequest signLeaseRequest = new SignLeaseRequest(this.ua, leasingAccount);
        signLeaseRequest.setApt(apt);
        signLeaseRequest.setAgent(agent);
        if (leasingAccount != null) {

            signLeaseRequest.setStatus("Contract preparation");
            signLeaseRequest.setOrderID(leasingAccount.getWorkQueue().getSignLeaseRequestList().size()+1);

            if( leasingAccount.getWorkQueue().getSignLeaseRequestList() == null ){
                leasingAccount.getWorkQueue().setSignLeaseRequestList(new ArrayList<SignLeaseRequest>());
            }
            leasingAccount.getWorkQueue().getSignLeaseRequestList().add(signLeaseRequest);
            
            if(  this.ua.getWorkQueue().getSignLeaseRequestList() == null ){
                 this.ua.getWorkQueue().setSignLeaseRequestList(new ArrayList<SignLeaseRequest>());
            }
            this.ua.getWorkQueue().getSignLeaseRequestList().add(signLeaseRequest) ;
            
            signLeaseRequest.toString();
            JOptionPane.showMessageDialog(null, "Leasing peopole will prepare your lease, Please wait for further instruction on payment");
            
        } else {
            JOptionPane.showMessageDialog(null, "no Leasing office");
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
