/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PropertyCompany.tenant;

import ui.PropertyCompany.tenant.*;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SignLeaseRequest;
import Business.property.Lease;
import Business.property.Rent;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class DetailLeaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form customerServiceJPanel
     */
     JPanel userProcessContainer;
    UserAccount ua;
    EcoSystem ecosystem;
    SignLeaseRequest slr;
   
    public DetailLeaseJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, SignLeaseRequest slr) {
         initComponents();
         this.ecosystem=business;
         this.ua = account;
         this. userProcessContainer = userProcessContainer;
         this.slr = slr ;
         populateTextField();
    }

     public  String dateToString(Date date){
         DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");  
         String strDate = dateFormat.format(date);  
         return strDate ;
   }
  
   private void populateTextField(){
            Lease lease =  this.slr.getLease() ;
            txtStartDate.setText(this.dateToString(lease.getStartDate()));
            
            txtEndDate.setText(this.dateToString(lease.getEndDate()));
            if(  this.slr.getLease().getRentList().size() == 0 ){
                txtRentalDate.setText(this.dateToString(lease.getRentalDate()));
            }//
            else{
                ArrayList<Rent> rents = this.slr.getLease().getRentList();
                Rent currentRent = rents.get(rents.size()-1);
                txtRentalDate.setText(this.dateToString(currentRent.getDate()) );
            }
                
            if( lease.getBalance() != null )
                txtBalance.setText(String.valueOf(lease.getBalance()));
            txtSecurityDeposit.setText(String.valueOf(lease.getSecurityDeposit()));
            txtBuilding.setText(lease.getBuilding().toString());
            txtTenant.setText(lease.getTenant().getUsername());
            if( lease.getTermination() != null )
                txtTerminationDate.setText(dateToString(lease.getTermination().getLeavingDate()));
            else
                txtTerminationDate.setText("No Termination");
            
            // populate rental list
           if( lease.getRentList().size() != 0 ){
                RentsCombobox.removeAllItems();
                ArrayList<Rent> rentList = lease.getRentList() ;
                for (Rent r : rentList ) {
                    RentsCombobox.addItem(r);
                }
           }//
           else{
               RentsCombobox.removeAllItems();
               RentsCombobox.addItem("No Payment");
           }
               
           
   }//
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        RentDetailJButton = new javax.swing.JButton();
        txtStartDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRentalDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSecurityDeposit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBuilding = new javax.swing.JTextField();
        txtTenant = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTerminationDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        RentsCombobox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setLayout(null);

        jLabel5.setText("Lease Detail");
        add(jLabel5);
        jLabel5.setBounds(276, 36, 159, 22);

        RentDetailJButton.setText("View Alll Rents Details");
        RentDetailJButton.setToolTipText("");
        RentDetailJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentDetailJButtonActionPerformed(evt);
            }
        });
        add(RentDetailJButton);
        RentDetailJButton.setBounds(472, 440, 185, 29);

        txtStartDate.setEnabled(false);
        add(txtStartDate);
        txtStartDate.setBounds(327, 91, 80, 26);

        jLabel1.setText("Start Date");
        add(jLabel1);
        jLabel1.setBounds(225, 96, 62, 16);

        jLabel3.setText("End Date");
        add(jLabel3);
        jLabel3.setBounds(225, 137, 56, 16);

        txtEndDate.setEnabled(false);
        add(txtEndDate);
        txtEndDate.setBounds(327, 132, 80, 26);

        jLabel4.setText("Rental Date");
        add(jLabel4);
        jLabel4.setBounds(225, 181, 72, 16);

        txtRentalDate.setEnabled(false);
        add(txtRentalDate);
        txtRentalDate.setBounds(327, 176, 80, 26);

        jLabel6.setText("Balance");
        add(jLabel6);
        jLabel6.setBounds(225, 225, 47, 16);

        txtBalance.setEnabled(false);
        add(txtBalance);
        txtBalance.setBounds(327, 220, 80, 26);

        jLabel7.setText("Security Deposit");
        add(jLabel7);
        jLabel7.setBounds(225, 269, 103, 16);

        txtSecurityDeposit.setEnabled(false);
        add(txtSecurityDeposit);
        txtSecurityDeposit.setBounds(327, 264, 80, 26);

        jLabel8.setText("Building");
        add(jLabel8);
        jLabel8.setBounds(225, 313, 51, 16);

        txtBuilding.setEnabled(false);
        add(txtBuilding);
        txtBuilding.setBounds(327, 308, 80, 26);

        txtTenant.setEnabled(false);
        add(txtTenant);
        txtTenant.setBounds(327, 352, 80, 26);

        jLabel9.setText("Tenant");
        add(jLabel9);
        jLabel9.setBounds(225, 357, 43, 16);

        jLabel10.setText("Termination Date");
        add(jLabel10);
        jLabel10.setBounds(225, 401, 109, 16);

        txtTerminationDate.setEnabled(false);
        add(txtTerminationDate);
        txtTerminationDate.setBounds(327, 396, 96, 26);

        jLabel11.setText("Rent History");
        add(jLabel11);
        jLabel11.setBounds(225, 445, 78, 16);

        backJButton1.setText("<< Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1);
        backJButton1.setBounds(139, 46, 97, 29);

        RentsCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(RentsCombobox);
        RentsCombobox.setBounds(327, 441, 96, 27);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel12.setText("jLabel4");
        add(jLabel12);
        jLabel12.setBounds(5, -4, 930, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void RentDetailJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentDetailJButtonActionPerformed
        // TODO add your handling code here:
        Rent selectedRent = (Rent)RentsCombobox.getSelectedItem();
        CardLayout layout =  (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new DetaiRentJPanel( userProcessContainer,  ua,  ecosystem, slr, selectedRent) );
        layout.next(userProcessContainer);
    }//GEN-LAST:event_RentDetailJButtonActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RentDetailJButton;
    private javax.swing.JComboBox<Object> RentsCombobox;
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBuilding;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtRentalDate;
    private javax.swing.JTextField txtSecurityDeposit;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTenant;
    private javax.swing.JTextField txtTerminationDate;
    // End of variables declaration//GEN-END:variables
}
