/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PropertyCompany.tenant;


import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SignLeaseRequest;
import Business.property.Lease;
import Business.property.Rent;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JPanel;


/**
 *
 * @author junyaoli
 */
public class DetaiRentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form customerServiceJPanel
     */
     JPanel userProcessContainer;
    UserAccount ua;
    EcoSystem ecosystem;
    SignLeaseRequest slr;
    Rent rent ;
   
    public DetaiRentJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, SignLeaseRequest slr, Rent sr) {
         initComponents();
         this.ecosystem=business;
         this.ua = account;
         this. userProcessContainer = userProcessContainer;
         this.slr = slr ;
         this.rent = sr;
         populateTextField();
    }

       public  String dateToString(Date date){
         DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");  
         String strDate = dateFormat.format(date);  
         return strDate ;
   }
   
    private void populateTextField(){
            Lease lease =  this.slr.getLease() ;
            txtDayToPay.setText(this.dateToString(this.rent.getDateToPay()));
            
            txtRentaldate.setText(this.dateToString(this.rent.getDate()));
                
            if( lease.getBalance() != null )
                txtBalance.setText(String.valueOf(lease.getBalance()));
            
            

            txtPayAmount.setText(String.valueOf(this.rent.getPayment().getPayAmount()));
            txtPayDate.setText(this.dateToString(this.rent.getDateToPay()));
            txtPayMethod.setText(this.rent.getPayment().getPayMethod());
               
           
   }//
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDayToPay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRentaldate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPayMethod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPayAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPayDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setEnabled(false);
        setLayout(null);

        jLabel5.setText("Rent  Detail");
        add(jLabel5);
        jLabel5.setBounds(400, 70, 159, 22);

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back-arrow.png"))); // NOI18N
        backJButton1.setBorderPainted(false);
        backJButton1.setDefaultCapable(false);
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1);
        backJButton1.setBounds(130, 220, 60, 60);

        jLabel1.setText("Day To Pay");
        add(jLabel1);
        jLabel1.setBounds(360, 130, 69, 16);

        txtDayToPay.setEnabled(false);
        add(txtDayToPay);
        txtDayToPay.setBounds(460, 130, 80, 26);

        jLabel3.setText("Rental Date");
        add(jLabel3);
        jLabel3.setBounds(360, 180, 72, 16);

        txtRentaldate.setEnabled(false);
        add(txtRentaldate);
        txtRentaldate.setBounds(460, 170, 80, 26);

        jLabel4.setText("Pay Method");
        add(jLabel4);
        jLabel4.setBounds(360, 220, 72, 16);

        txtPayMethod.setEnabled(false);
        txtPayMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayMethodActionPerformed(evt);
            }
        });
        add(txtPayMethod);
        txtPayMethod.setBounds(460, 210, 80, 26);

        jLabel6.setText("Balance");
        add(jLabel6);
        jLabel6.setBounds(360, 260, 47, 16);

        txtBalance.setEnabled(false);
        add(txtBalance);
        txtBalance.setBounds(460, 260, 80, 26);

        jLabel7.setText("Pay Amount");
        add(jLabel7);
        jLabel7.setBounds(360, 310, 75, 16);

        txtPayAmount.setEnabled(false);
        add(txtPayAmount);
        txtPayAmount.setBounds(460, 300, 80, 26);

        jLabel8.setText("Pay Date");
        add(jLabel8);
        jLabel8.setBounds(360, 350, 54, 16);

        txtPayDate.setEnabled(false);
        add(txtPayDate);
        txtPayDate.setBounds(460, 350, 80, 26);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel9.setText("jLabel4");
        add(jLabel9);
        jLabel9.setBounds(5, -4, 930, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void txtPayMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayMethodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtDayToPay;
    private javax.swing.JTextField txtPayAmount;
    private javax.swing.JTextField txtPayDate;
    private javax.swing.JTextField txtPayMethod;
    private javax.swing.JTextField txtRentaldate;
    // End of variables declaration//GEN-END:variables
}
