/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PropertyCompany.tenant;


import Business.EcoSystem;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.SignLeaseRequest;
import Business.property.Lease;
import Business.property.Payment;
import Business.property.Rent;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class PayLeaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form customerServiceJPanel
     */
     JPanel userProcessContainer;
    UserAccount ua;
    EcoSystem ecosystem;
    SignLeaseRequest slr;
   
    public PayLeaseJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, SignLeaseRequest slr) {
         initComponents();
         this.ecosystem=business;
         this.ua = account;
         this. userProcessContainer = userProcessContainer;
         this.slr = slr ;
         txtBalance.setEditable(true);
         txtBalance.setEnabled(true);
         populateTextField();
    }

       public  String dateToString(Date date){
         DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");  
         String strDate = dateFormat.format(date);  
         return strDate ;
   }
    
   private void populateTextField(){
            Lease lease =  this.slr.getLease() ;
            txtStartDate.setText(this.dateToString(lease.getStartDate()));
            
            txtEndDate.setText(this.dateToString(lease.getEndDate()));             
            if( lease.getBalance() != null )
                txtBalance.setText(String.valueOf(lease.getBalance()));
            txtSecurityDeposit.setText(String.valueOf(lease.getSecurityDeposit()));
            txtBuilding.setText(lease.getBuilding().toString());
            txtRentPrice.setText(String.valueOf(lease.getBuilding().getMonthlyrent()));
            
            
            Double minimumBalance = Double.valueOf(lease.getBuilding().getMonthlyrent())  ;
            if(  this.slr.getLease().getRentList().size() == 0 ){
                minimumBalance = minimumBalance +  this.slr.getLease().getSecurityDeposit() ;
                txtRentalDate.setText(this.dateToString(lease.getRentalDate()));
            }//
            else{
                ArrayList<Rent> rents = this.slr.getLease().getRentList();
                Rent currentRent = rents.get(rents.size()-1);
                txtRentalDate.setText(this.dateToString(this.getNextMonth(currentRent.getDate())) );
            }
            txtMinimumBalance.setText(String.valueOf(minimumBalance));       
                                          
   }//
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRentalDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSecurityDeposit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBuilding = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnSubmitPayment = new javax.swing.JButton();
        RentsCombobox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtRentPrice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMinimumBalance = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        jLabel5.setText("Lease Detail");

        txtStartDate.setEnabled(false);

        jLabel1.setText("Start Date");

        jLabel3.setText("End Date");

        txtEndDate.setEnabled(false);

        jLabel4.setText("Rental Date");

        txtRentalDate.setEnabled(false);

        jLabel6.setText("Balance");

        txtBalance.setEnabled(false);

        jLabel7.setText("Security Deposit");

        txtSecurityDeposit.setEnabled(false);

        jLabel8.setText("Building");

        txtBuilding.setEnabled(false);

        jLabel11.setText("Pay Method");

        btnSubmitPayment.setText("Submit Payment");
        btnSubmitPayment.setToolTipText("");
        btnSubmitPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPaymentActionPerformed(evt);
            }
        });

        RentsCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Method", "Check", "Credit Card", "Cash" }));
        RentsCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentsComboboxActionPerformed(evt);
            }
        });

        jLabel12.setText("Rent Price");

        txtRentPrice.setEnabled(false);
        txtRentPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRentPriceActionPerformed(evt);
            }
        });

        jLabel13.setText("Minimum Balance");

        txtMinimumBalance.setToolTipText("");
        txtMinimumBalance.setEnabled(false);
        txtMinimumBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinimumBalanceActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(btnSubmitPayment)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(24, 24, 24)
                                    .addComponent(txtSecurityDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMinimumBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(49, 49, 49)
                                    .addComponent(txtRentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(RentsCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(57, 57, 57)
                                .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 616, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(backJButton)
                    .addContainerGap(810, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSecurityDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMinimumBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(RentsCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnSubmitPayment)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(backJButton)
                    .addContainerGap(521, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

      public  Date getNextMonth(Date date){
          Calendar cal=Calendar.getInstance();
          cal.setTime(date);
          cal.set(Calendar.MONTH, date.getMonth()+1);
          Date dueDate = new Date(cal.getTimeInMillis());
         return dueDate ;
     } //
    
    private void btnSubmitPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPaymentActionPerformed
        // TODO add your handling code here:
        
        Double minBalance = Double.valueOf(this.slr.getBuilding().getMonthlyrent())  ;
        if(  this.slr.getLease().getRentList().size() == 0 )
           minBalance = minBalance +  this.slr.getLease().getSecurityDeposit() ;
        
        String payMethod = RentsCombobox.getSelectedItem().toString();
        Double balance ;
        // 
        if ( payMethod == null || payMethod.equals("Select Method") ) {
            JOptionPane.showMessageDialog(null, "Please Select Pay Method", "Info", JOptionPane.INFORMATION_MESSAGE);
            return ;
        } // if
        try{
            balance =  Double.valueOf(txtBalance.getText())  ;
            if( balance >= minBalance  ){
                // First Rent
                Rent rent = new Rent() ;
                rent.setPrice(Double.valueOf(this.slr.getBuilding().getMonthlyrent()));
                rent.setLateFee(0.0);
                rent.setLease(this.slr.getLease());
                if(  this.slr.getLease().getRentList().size() != 0 ){
                    ArrayList<Rent> rents = this.slr.getLease().getRentList();
                   Rent currentRent = rents.get(rents.size()-1);
                    rent.setDate( this.getNextMonth(currentRent.getDate()) );
                    rent.setDateToPay( this.getNextMonth(currentRent.getDate()) );
                } // if
                else{
                    rent.setDate(this.slr.getLease().getStartDate());
                    rent.setDateToPay(this.slr.getLease().getStartDate());
                }
                // Payment
                Payment payment = new Payment();
                payment.setPayAmount(Double.valueOf(minBalance));
                payment.setPayDate(rent.getDateToPay());
                payment.setPayMethod(payMethod);
                payment.setRent(rent);
                rent.setPayment(payment);
                //Lease
                this.slr.getLease().addRent(rent);
                // Set Status.
                this.slr.setStatus("Payment Reviewing");
                this.slr.getLease().setBalance(balance);
                
                JOptionPane.showMessageDialog(null, "You Select Method" +   payMethod  +
                        "  Total Balance deposit " + String.valueOf(balance) + " dollars ", "Info", JOptionPane.INFORMATION_MESSAGE);
            } // if
            else{
                JOptionPane.showMessageDialog(null, "Please Pay more minimum balance", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
          
        }
        catch(Exception e ){
             JOptionPane.showMessageDialog(null, "Please Input Correct Integer Balance", "Info", JOptionPane.INFORMATION_MESSAGE);
             return ;
        }
    }//GEN-LAST:event_btnSubmitPaymentActionPerformed

    private void txtMinimumBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinimumBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinimumBalanceActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void RentsComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentsComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentsComboboxActionPerformed

    private void txtRentPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRentPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRentPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> RentsCombobox;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSubmitPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBuilding;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtMinimumBalance;
    private javax.swing.JTextField txtRentPrice;
    private javax.swing.JTextField txtRentalDate;
    private javax.swing.JTextField txtSecurityDeposit;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
}
