/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PropertyCompany.tenant;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VisitRequest;
import Util.Map;
import Util.MapJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class viewAppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewAppointmentJPanel
     */
    JPanel userProcessContainer;
    UserAccount ua;
    EcoSystem ecosystem;
    VisitRequest request;
    Map maojframe;
    public viewAppointmentJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business,VisitRequest request) throws URISyntaxException, IOException {
         initComponents();
         this.ecosystem=business;
         this.ua = account;
         this. userProcessContainer = userProcessContainer;
         this. request = request;
         maojframe=new Map(userProcessContainer, request.getBuilding());
         maojframe.setVisible(false);
         updatemessage();
    }
    public void updatemessage(){
        try {
            if (request.getAgent().equals(ua)) {
                agentjLabel.setText(request.getCustomer().toString());
            }else
                agentjLabel.setText(request.getAgent().toString());
            
            aptjLabel.setText(request.getBuilding().getAddress());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
            String megString="";
            for(String meg : request.getMessage()){
                megString+=meg+"\n";
                jTextArea1.setText(megString);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        agentjLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aptjLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jButton2.setText("Reply");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(157, 285, 78, 29);

        jLabel3.setText("Chat with: ");
        add(jLabel3);
        jLabel3.setBounds(112, 106, 68, 16);

        agentjLabel.setText("<value>");
        add(agentjLabel);
        agentjLabel.setBounds(186, 106, 53, 16);

        jLabel5.setText("Appartment: ");
        add(jLabel5);
        jLabel5.setBounds(273, 106, 82, 16);

        aptjLabel.setText("<value>");
        add(aptjLabel);
        aptjLabel.setBounds(361, 106, 53, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2);
        jScrollPane2.setBounds(112, 132, 359, 128);

        jLabel2.setText("Message");
        add(jLabel2);
        jLabel2.setBounds(253, 73, 54, 16);

        jTextField1.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jTextField1.setText("Please imput message");
        add(jTextField1);
        jTextField1.setBounds(241, 272, 221, 53);

        jButton3.setText("Map");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(420, 101, 75, 29);

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(112, 26, 97, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(5, -4, 930, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        mgnaptJPanel jpanel = (mgnaptJPanel) component;
        jpanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
            String meg =new Date().toString()+"\n";
            meg =meg+ua.getUsername()+": ";
            meg=meg+jTextField1.getText()+"";
            System.out.println(meg);
            request.addMessage(meg);
        
        updatemessage();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//        userProcessContainer.add(new MapJPanel(userProcessContainer,request.getBuilding()));
//        layout.next(userProcessContainer);
            maojframe.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agentjLabel;
    private javax.swing.JLabel aptjLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
