/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliner;
import Business.AirlinerDirectory;
import Images.StyledButton;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class CreateNewAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirlinerJPanel
     */
    private JPanel cardSequenceJPanel;
    private AirlinerDirectory airlinerDir;
    CreateNewAirlinerJPanel(JPanel cardSequenceJPanel, AirlinerDirectory airlinerDir) {
         initComponents();
         this.airlinerDir = airlinerDir;
         this.cardSequenceJPanel = cardSequenceJPanel;
         backBtn.setUI(new StyledButton());
         createBtn.setUI(new StyledButton());
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void emptyInputFields(){
        nameTxtField.setText("");
        codeTxtField.setText("");
        countriesOperatedTxtField.setText("");
        originCountryTxtField.setText("");
        noOfFlightsTxtField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        codeTxtField = new javax.swing.JTextField();
        countriesOperatedTxtField = new javax.swing.JTextField();
        originCountryTxtField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        noOfFlightsTxtField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Airliner");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 155, -1, -1));

        jLabel2.setText("Code");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 237, -1, -1));

        jLabel3.setText("Countries Operated");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 327, -1, -1));

        jLabel4.setText("Origin Country");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 417, -1, -1));
        add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 145, 198, 37));
        add(codeTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 228, 198, 35));
        add(countriesOperatedTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 318, 198, 34));
        add(originCountryTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 407, 198, 36));

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 527, 134, 49));

        jLabel5.setText("Number of Flight ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 494, -1, -1));
        add(noOfFlightsTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 483, 196, 38));

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 59, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Create Airliner");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 67, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        if("".equals(nameTxtField.getText())){
            nameTxtField.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel1.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter Name");
            return;
        }
        else{
            nameTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jLabel1.setForeground(Color.BLACK);
        }
        if("".equals(codeTxtField.getText())){
            codeTxtField.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel2.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter Code");
            return;
        }
        else{
            codeTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jLabel2.setForeground(Color.BLACK);
        }
        
        try{
            Double.parseDouble(countriesOperatedTxtField.getText());
            countriesOperatedTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jLabel3.setForeground(Color.BLACK);
        }
        catch(Exception e){
            countriesOperatedTxtField.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel3.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter number for Countries operated");
            return;
        }
        if("".equals(originCountryTxtField.getText())){
            originCountryTxtField.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel4.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter Origin Country");
            return;
        }
        else{
            originCountryTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jLabel4.setForeground(Color.BLACK);
        }
        try{
            Integer.parseInt(noOfFlightsTxtField.getText());
            noOfFlightsTxtField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jLabel5.setForeground(Color.BLACK);
        }
        catch(Exception e){
            noOfFlightsTxtField.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel4.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter number for Fleet");
            return;
        }
        
        Airliner newAirliner = new Airliner();
        newAirliner.setName(nameTxtField.getText());
        newAirliner.setAirlineCode(codeTxtField.getText());
        newAirliner.setCountriesOperated((int)Double.parseDouble(countriesOperatedTxtField.getText()));
        newAirliner.setNumOfFlights((int)Double.parseDouble(noOfFlightsTxtField.getText()));
        newAirliner.setOriginCountry(originCountryTxtField.getText());
        airlinerDir.addAirliner(newAirliner);
        JOptionPane.showMessageDialog(null, "Airliner Created Successfully");
        emptyInputFields();
    }//GEN-LAST:event_createBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        
        Component[] components = cardSequenceJPanel.getComponents();
        for(Component component: components){
            if(component instanceof ManageAirlinersJPanel){
                ManageAirlinersJPanel mpp = (ManageAirlinersJPanel) component;
                mpp.populateTable();
            }
        }
        
        layout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField codeTxtField;
    private javax.swing.JTextField countriesOperatedTxtField;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JTextField noOfFlightsTxtField;
    private javax.swing.JTextField originCountryTxtField;
    // End of variables declaration//GEN-END:variables
}
