/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Util;

import Business.Employee.Propority;
import com.kingaspx.util.BrowserUtil;
import com.kingaspx.version.Version;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.dom.By;
import com.teamdev.jxbrowser.chromium.dom.DOMDocument;
import com.teamdev.jxbrowser.chromium.dom.DOMElement;
import com.teamdev.jxbrowser.chromium.dom.DOMInputElement;
import com.teamdev.jxbrowser.chromium.events.FinishLoadingEvent;
import com.teamdev.jxbrowser.chromium.events.LoadAdapter;
import com.teamdev.jxbrowser.chromium.events.TitleListener;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.Panel;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;


/**
 *
 * @author junyaoli
 */
public class Map extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
     Propority propority;
    JPanel userProcessContainer;
    String aptaddress;
    public Map(JPanel userProcessContainer,Propority p)throws URISyntaxException, IOException {
        initComponents();
        propority = p;
        aptaddress=propority.getAddress();
        this.userProcessContainer=userProcessContainer;
        open_site();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        jLabel1.setText(aptaddress);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        refreshjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Google");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 140, 140));
        jLabel1.setText("<value>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 320, 50));

        jButton1.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 51));
        jButton1.setText("Locate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 21, 141, 45));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 3));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 800, 522));

        refreshjButton.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        refreshjButton.setForeground(new java.awt.Color(51, 0, 51));
        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(refreshjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 21, 107, 45));

        jLabel2.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(226, 140, 140));
        jLabel2.setText("Your Apartment:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 50));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(802, 624));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    DOMDocument doc = browser.getDocument();

    DOMElement address_element = doc.findElement(By.id("address"));
    DOMElement search_element = doc.findElement(By.id("submit"));
    DOMElement button = (DOMElement) search_element;

    DOMInputElement address = (DOMInputElement) address_element;
    address.setValue(aptaddress);

    button.click();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
        // TODO add your handling code here:
        open_site(); 
    }//GEN-LAST:event_refreshjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    JFrame f = new Map();
//                    f.setVisible(true);
//                } catch (URISyntaxException ex) {
//                    Logger.getLogger(Map.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (IOException ex) {
//                    Logger.getLogger(Map.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton refreshjButton;
    // End of variables declaration//GEN-END:variables
    
    Browser browser;
    BrowserView view;
    
    private void open_site(){
        //System.setProperty("jxbrowser.license.key", "your_license_key");//Version.V6_22
       
        BrowserUtil.setVersion(Version.V6_22);
        browser =new Browser();
        view=new BrowserView(browser);
        jPanel2.add(view,BorderLayout.CENTER);
        
        browser.addTitleListener((te) -> {
            setTitle(te.getTitle());
        });
        browser.addConsoleListener((ce) -> {
            System.out.println("Log: "+ ce.getMessage());
        });
        browser.addLoadListener(new LoadAdapter() {
            @Override
            public void onFinishLoadingFrame(FinishLoadingEvent evt){
                evt.getBrowser().setZoomLevel(-2);
            }
            });
        ///Users/junyaoli/Documents/CYN_LJY_HHZ/java_jar/html
        browser.loadURL("C:\\Users\\Mchig\\Desktop\\Info5100\\final_project\\CYN_LJY_HHZ\\java_jar\\html\\search.html");//testbb，marker版本，import,search
    }
    
}
