/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.InvestmentCompany;

import Business.EcoSystem;
import Business.Employee.CleaningStaff;
import Business.Employee.Decorator;
import Business.Employee.Landlord;
import Business.Employee.Propority;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.BoardMemberOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.FurnishingRequest;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yiningchen
 */
public class FindFurnishingJPanel extends javax.swing.JPanel {

    private FurnishingRequest request;
    private UserAccount userAccount;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem ecosystem;

    /**
     * Creates new form FindFurnishingJPanel
     */
    public FindFurnishingJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        //this.enterprise = enterprise;
        this.userAccount = account;
        this.ecosystem = ecosystem;
        this.request = new FurnishingRequest();
        for (Network network : ecosystem.getNetworkList()) {
            NetWorkCombobox.addItem(network.getName());

        }

        populateproporityTable();

    }

    public void populatEnterpriseCombo(String net) {
        EnterpriseCombobox.removeAllItems();
        for (Enterprise enterprise : ecosystem.findNetwork(net).getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnterpriseType.Furnishing.getValue())) {
                EnterpriseCombobox.addItem(enterprise.getName());
            }

        }
    }

    public void populatchargefee() {
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            return;
        }
        String dec = decoratorCombobox.getSelectedItem().toString();
        String network = NetWorkCombobox.getSelectedItem().toString();
        String enter = EnterpriseCombobox.getSelectedItem().toString();
        Enterprise enterprise = ecosystem.findNetwork(network).getEnterpriseDirectory().findenterprise(enter);
        Organization organization = enterprise.getOrganizationDirectory().findorganization("Furnishing Organization");
        int fee = organization.getDecoratorDirectory().findDecorator(dec).getFeepersquarefeet();

        int sqtfeet = Integer.parseInt(jTable1.getValueAt(row, 3).toString());
        int total = sqtfeet * fee;
        txtfee.setText(Integer.toString(total));
        JOptionPane.showMessageDialog(null, "You total quote for decorate is " + total);

    }

    public void populatDecoratorCombo() {
        decoratorCombobox.removeAllItems();
        String network = NetWorkCombobox.getSelectedItem().toString();
        String enter = EnterpriseCombobox.getSelectedItem().toString();

        Enterprise enterprise = ecosystem.findNetwork(network).getEnterpriseDirectory().findenterprise(enter);
        Organization organization = enterprise.getOrganizationDirectory().findorganization("Furnishing Organization");
        for (Decorator decorator : organization.getDecoratorDirectory().getDecoratorList()) {
            decoratorCombobox.addItem(decorator.getName());
        }
    }

    public void populateproporityTable() {

        Landlord landlord = userAccount.getLandlord();

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        List<Propority> prolist = landlord.getProporityCatalog();
        if (prolist != null) {
            for (Propority p : prolist) {
                Object row[] = new Object[5];
                row[0] = p.getNickname();
                row[1] = p.getAddress();
                row[2] = p.getAptNo();
                row[3] = p.getSquareFeet();
                row[4] = p.getURL();
                
                dtm.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        assignjButton = new javax.swing.JButton();
        decoratorCombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        txtfee = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EnterpriseCombobox = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        NetWorkCombobox = new javax.swing.JComboBox<>();
        backJButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Decorator");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(363, 382, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Property nickName", "Address", "apt No", "Square feet", "URL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 910, 180);

        assignjButton.setText("Comfirm and Check Out");
        assignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignjButtonActionPerformed(evt);
            }
        });
        add(assignjButton);
        assignjButton.setBounds(363, 466, 238, 41);

        decoratorCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        decoratorCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decoratorComboboxActionPerformed(evt);
            }
        });
        add(decoratorCombobox);
        decoratorCombobox.setBounds(459, 381, 212, 38);

        jLabel1.setText("Total Charges base on square feet");
        add(jLabel1);
        jLabel1.setBounds(363, 425, 214, 26);

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-christmas-tree-50.png"))); // NOI18N
        enterpriseLabel1.setText("Furnishing Company Request");
        add(enterpriseLabel1);
        enterpriseLabel1.setBounds(330, 0, 328, 60);

        txtfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfeeActionPerformed(evt);
            }
        });
        add(txtfee);
        txtfee.setBounds(583, 425, 105, 26);

        jButton2.setText("get Quote");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(700, 425, 106, 29);

        jLabel2.setText("Network");
        add(jLabel2);
        jLabel2.setBounds(365, 262, 53, 16);

        jLabel3.setText("Enterprise");
        add(jLabel3);
        jLabel3.setBounds(365, 301, 63, 16);

        EnterpriseCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterpriseComboboxActionPerformed(evt);
            }
        });
        add(EnterpriseCombobox);
        EnterpriseCombobox.setBounds(440, 297, 136, 27);

        jButton4.setText("Find Decorator");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(363, 330, 205, 45);

        NetWorkCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetWorkComboboxActionPerformed(evt);
            }
        });
        add(NetWorkCombobox);
        NetWorkCombobox.setBounds(434, 258, 142, 27);

        backJButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back-arrow.png"))); // NOI18N
        backJButton1.setToolTipText("");
        backJButton1.setBorderPainted(false);
        backJButton1.setContentAreaFilled(false);
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1);
        backJButton1.setBounds(160, 260, 57, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(5, -4, 930, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void assignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignjButtonActionPerformed
        // TODO add your handling code here:
        String network = NetWorkCombobox.getSelectedItem().toString();
        String enter = EnterpriseCombobox.getSelectedItem().toString();
        Enterprise enterprise = ecosystem.findNetwork(network).getEnterpriseDirectory().findenterprise(enter);
        Organization organization = enterprise.getOrganizationDirectory().findorganization("Furnishing Organization");

        int row = jTable1.getSelectedRow();
        if (row < 0) {
            return;
        }
        String propNickname = jTable1.getValueAt(row, 0).toString();
          if (txtfee.getText()==""|| decoratorCombobox.getSelectedItem().equals(null)) {
            return;
        }else{
        Double fee = Double.parseDouble(txtfee.getText());
        String decname = decoratorCombobox.getSelectedItem().toString();
        int sqtfeet = Integer.parseInt(jTable1.getValueAt(row, 3).toString());
        UserAccount decaccount = organization.getUserAccountDirectory().findUser(decname);
        if (decaccount != null) {
            request.setFeeString(fee);
            request.setRequirement(propNickname);
            request.setCustomerAccount(userAccount);
            request.setReceiver(decaccount);
            request.setStatus("pending");
            request.setTitle(propNickname + " Decotator request");
            request.setSqtfeet(sqtfeet);
            request.setComment(network);

            userAccount.getWorkQueue().getWorkRequestList().add(request);
            organization.getUserAccountDirectory().findUser(decname).getWorkQueue().getFurnishingRequestList().add(request);

            JOptionPane.showMessageDialog(null, "assign successfully");
        }
        }
    }//GEN-LAST:event_assignjButtonActionPerformed

    private void decoratorComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decoratorComboboxActionPerformed
        // TODO add your handling code here:

        // populatchargefee();
    }//GEN-LAST:event_decoratorComboboxActionPerformed

    private void txtfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "please select a property");
        } else;
        populatchargefee();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EnterpriseComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterpriseComboboxActionPerformed

    }//GEN-LAST:event_EnterpriseComboboxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        populatDecoratorCombo();
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void NetWorkComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetWorkComboboxActionPerformed
        // TODO add your handling code here:
        String network = NetWorkCombobox.getSelectedItem().toString();
        if (network != null) {
            populatEnterpriseCombo(network);
        }
    }//GEN-LAST:event_NetWorkComboboxActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LandlordWorkAreaJPanel dwjp = (LandlordWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EnterpriseCombobox;
    private javax.swing.JComboBox<String> NetWorkCombobox;
    private javax.swing.JButton assignjButton;
    private javax.swing.JButton backJButton1;
    private javax.swing.JComboBox<String> decoratorCombobox;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtfee;
    // End of variables declaration//GEN-END:variables
}
