/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Customer;
import Business.Flight;
import Business.Ticket;
import Images.StyledButton;
import UserInterface.ManageAirliners.ManageAirlinersJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class BookingInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingInformationJPanel
     */
    private JPanel cardSequenceJPanel;
    private String seatBooked;
    private ArrayList<Flight> bookedFlight;
    private ArrayList<Ticket> bookedTicket;
    private Ticket selectedticket;
    private Customer customer;
    BookingInformationJPanel(JPanel cardSequenceJPanel, ArrayList<Flight> bookedFlight,Customer customer) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.bookedFlight = bookedFlight;
        this.customer=customer;
        bookedTicket=customer.getTicketBooked();
        populateTable();
        backBtn.setUI(new StyledButton());
         selectjButton.setUI(new StyledButton());
         jButton1.setUI(new StyledButton());
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

      public void populateTable(){
         DefaultTableModel  dtm;
        dtm = (DefaultTableModel)tblMasterFlight.getModel();
        dtm.setRowCount(0);

        for(Ticket a : bookedTicket){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = a.getFlight().getOwner();
            row[1] = a;
            row[2] = a.getFlight().getSource();
            row[3] = a.getFlight().getDestination();
            row[4] = a.getFlight().getDepTime();
            row[5] = a.getFlight().getArrTime();
            row[6] = a.getFlight().getDuration();
            row[7] = a.getFlight().getDate();
            row[8] = a.getFlight().getOtod();
            row[9] = a.getSeat();
            
            dtm.addRow(row);
        }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMasterFlight = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        seatjComboBox = new javax.swing.JComboBox<>();
        selectjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Booking Information");

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        tblMasterFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Airliner", "Flight Number", "Departing from", "Destination", "Departure Time", "Arrival Time", "Duration", "Date", "Time of Day", "Seat"
            }
        ));
        jScrollPane1.setViewportView(tblMasterFlight);

        jButton1.setText("Choose a seat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        seatjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectjButton.setText("Select a flight");
        selectjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(seatjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(selectjButton)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(backBtn)
                            .addGap(181, 181, 181)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, selectjButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectjButton))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, selectjButton});

    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();

        Component[] components = cardSequenceJPanel.getComponents();
        for(Component component: components){
            if(component instanceof CustomerInformationJPanel){
                CustomerInformationJPanel mpp = (CustomerInformationJPanel) component;
                mpp.populateTable();
            }
        }

        layout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void selectjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectjButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow =tblMasterFlight.getSelectedRow();
        if (selectedRow>=0) {
               Ticket t= (Ticket)tblMasterFlight.getValueAt(selectedRow, 1);
               selectedticket=t;
               seatjComboBox.removeAllItems();
               for (String seat : selectedticket.getFlight().getSeats().getSeat()) {
                  seatjComboBox.addItem(seat);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row!","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_selectjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        seatBooked=(String)seatjComboBox.getSelectedItem();
          try {
            String temp = selectedticket.getSeat();
              if (temp!=null) {
                  if (!selectedticket.getFlight().getSeats().getSeat().contains(temp)) {
                System.out.println("1"+temp);
                selectedticket.getFlight().getSeats().getSeat().add(temp);
                }
              }
            selectedticket.setSeat(seatBooked);
            selectedticket.getFlight().getSeats().getSeat().remove(seatBooked);
            populateTable();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Please select a row!","Warning",JOptionPane.WARNING_MESSAGE);
       
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> seatjComboBox;
    private javax.swing.JButton selectjButton;
    private javax.swing.JTable tblMasterFlight;
    // End of variables declaration//GEN-END:variables
}
