/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MasterAirlinerFlightSchedule;

import Business.Flight;
import Business.FlightDirectory;
import Business.Seats;
import Images.StyledButton;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class CreateFlightScheduleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateFlightScheduleJPanel
     */
    private JPanel cardSequenceJPanel;
    private FlightDirectory flightDir;
    public CreateFlightScheduleJPanel(JPanel cardSequenceJPanel,FlightDirectory flightDir, String airlinerName) {
        initComponents();
        airlinerTF.setText(airlinerName);
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.flightDir = flightDir;
        otodComboBox.setSelectedItem("Select Option");
        CreateBtn.setUI(new StyledButton());
        backBtn.setUI(new StyledButton());
    }
    public void emptyInputFields(){
        airlinerTF.setText("");
        flightNumTF.setText("");
        sourceTF.setText("");
        destinationTF.setText("");
        departureTimeTF.setText("");
        arrivalTimeTF.setText("");
        durationTF.setText("");
        dateTF.setText("");
        priceTF.setText("");
        capacityTF.setText("");
        otodComboBox.setSelectedItem("Select Option");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        airlinerTF = new javax.swing.JTextField();
        flightNumTF = new javax.swing.JTextField();
        sourceTF = new javax.swing.JTextField();
        destinationTF = new javax.swing.JTextField();
        departureTimeTF = new javax.swing.JTextField();
        arrivalTimeTF = new javax.swing.JTextField();
        durationTF = new javax.swing.JTextField();
        dateTF = new javax.swing.JTextField();
        CreateBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        otodComboBox = new javax.swing.JComboBox<>();
        capacityTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Create Flight Schedule");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 22, -1, -1));

        jLabel2.setText("Air Liner");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 71, -1, -1));

        jLabel3.setText("Flight Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 115, -1, -1));

        jLabel4.setText("Departing from");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 159, -1, -1));

        jLabel5.setText("Destination");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 203, -1, -1));

        jLabel6.setText("Departure Time");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 247, -1, -1));

        jLabel7.setText("Arrival Time");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 291, -1, -1));

        jLabel8.setText("Duration");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 335, -1, -1));

        jLabel9.setText("Date (dd-mm-yyyy)");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 448, -1, 26));

        airlinerTF.setEnabled(false);
        airlinerTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerTFActionPerformed(evt);
            }
        });
        add(airlinerTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 66, 131, -1));

        flightNumTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightNumTFActionPerformed(evt);
            }
        });
        add(flightNumTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 110, 131, -1));

        sourceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceTFActionPerformed(evt);
            }
        });
        add(sourceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 154, 131, -1));
        add(destinationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 198, 131, -1));
        add(departureTimeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 242, 131, -1));
        add(arrivalTimeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 286, 131, -1));

        durationTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationTFActionPerformed(evt);
            }
        });
        add(durationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 330, 131, -1));
        add(dateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 448, 131, -1));

        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });
        add(CreateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 563, 106, 49));

        jLabel11.setText("Operated Time of Day");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 496, -1, -1));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, -1, -1));

        otodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option", "Morning", "Afternoon", "Evening", "Night" }));
        add(otodComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 492, -1, -1));

        capacityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacityTFActionPerformed(evt);
            }
        });
        add(capacityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 404, 131, -1));

        jLabel10.setText("Capacity");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 409, -1, -1));

        priceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTFActionPerformed(evt);
            }
        });
        add(priceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 368, 131, -1));

        jLabel12.setText("Price");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 373, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        // TODO add your handling code here:
        if("".equals(airlinerTF.getText())){
            JOptionPane.showMessageDialog(null, "Please enter airliner");
            return;
        }
        if("".equals(flightNumTF.getText())){
            flightNumTF.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel3.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter FlightNumber");
            return;
        }
        else{
            flightNumTF.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jLabel3.setForeground(Color.BLACK);
        }
         if("".equals(capacityTF.getText())){
            JOptionPane.showMessageDialog(null, "Please enter Capacity");
            return;
        }
        if("".equals(sourceTF.getText())){
            JOptionPane.showMessageDialog(null, "Please enter Source");
            return;
        }
         if("".equals(destinationTF.getText())){
            JOptionPane.showMessageDialog(null, "Please enter Destination");
            return;
        }
        
        if("".equals(arrivalTimeTF.getText())){
            JOptionPane.showMessageDialog(null, "Please enter arrival Time in HH:MM");
            return;
        }else{
            Pattern p = Pattern.compile("^(0[0-9]|1[0-9]|2[0-3]|[0-9]):[0-5][0-9]$");
            Matcher m = p.matcher(arrivalTimeTF.getText());
            boolean b = m.matches();
            if(!b){
                JOptionPane.showMessageDialog(null, "Please enter arrival Time in HH:MM");
                return;
            }
        }
        if("".equals(departureTimeTF.getText())){
            JOptionPane.showMessageDialog(null, "Please enter Departure Time in HH:MM");
            return;
        }
        else{
            Pattern p = Pattern.compile("^(0[0-9]|1[0-9]|2[0-3]|[0-9]):[0-5][0-9]$");
            Matcher m = p.matcher(departureTimeTF.getText());
            boolean b = m.matches();
            if(!b){
                JOptionPane.showMessageDialog(null, "Please enter departure Time in HH:MM");
                return;
            }
        }
        
        if("".equals(flightNumTF.getText())){
            JOptionPane.showMessageDialog(null, "Please enter Flight Number");
            return;
        }
        if("".equals(priceTF.getText())){
            JOptionPane.showMessageDialog(null, "Please enter Price");
            return;
        }
        if("".equals(dateTF.getText())){
            JOptionPane.showMessageDialog(null, "Please enter Date");
            return;
        }
        
        if("".equals(sourceTF.getText())){
            JOptionPane.showMessageDialog(null, "Please enter Source");
            return;
        }
        if("".equals(destinationTF.getText())){
            JOptionPane.showMessageDialog(null, "Please enter Destination");
            return;
        }
        
        
        try{
           Integer.parseInt(durationTF.getText());        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, "Please enter valid duartion");
           return;    }
        if("".equals(otodComboBox.getSelectedItem().equals("Select Option"))){
            JOptionPane.showMessageDialog(null, "Please enter Code");
            return;
        }
        
        if(otodComboBox.getSelectedItem().equals("Select Option")){
            JOptionPane.showMessageDialog(null, "Please select an option below");
            return;
        }
        
        Flight newFlight = new Flight();
        newFlight.setOwner(airlinerTF.getText());
        newFlight.setFlightNumber(flightNumTF.getText());
        newFlight.setSource(sourceTF.getText());
        newFlight.setDestination(destinationTF.getText());
        newFlight.setDepTime(departureTimeTF.getText());
        newFlight.setArrTime(arrivalTimeTF.getText());
        newFlight.setPrice(Double.parseDouble(priceTF.getText()));
        newFlight.setSeats(Integer.parseInt(capacityTF.getText()));
        newFlight.setDuration((int)Double.parseDouble(durationTF.getText())); 
        
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String dateInString = dateTF.getText();

        try {

            Date date = formatter.parse(dateInString);
            SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
            dateFormat.format(date);
            //System.out.println(formatter.format(date));
            newFlight.setDate(date);

        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Please enter date in dd-MM-yyyy format");
            return;
        }

        
       
        newFlight.setOtod(otodComboBox.getSelectedItem().toString());
        flightDir.addFlight(newFlight);
        JOptionPane.showMessageDialog(null, "Flight Created Successfully");
        emptyInputFields();
    }//GEN-LAST:event_CreateBtnActionPerformed

    private void airlinerTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlinerTFActionPerformed

    private void flightNumTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightNumTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightNumTFActionPerformed

    private void sourceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceTFActionPerformed

    private void durationTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTFActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();

        Component[] components = cardSequenceJPanel.getComponents();
        for(Component component: components){
            if(component instanceof ManageAirlinerFlightScheduleJPanel){
                ManageAirlinerFlightScheduleJPanel mpp = (ManageAirlinerFlightScheduleJPanel) component;
                mpp.populateTable();
            }
        }

        layout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void capacityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacityTFActionPerformed

    private void priceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateBtn;
    private javax.swing.JTextField airlinerTF;
    private javax.swing.JTextField arrivalTimeTF;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField capacityTF;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField departureTimeTF;
    private javax.swing.JTextField destinationTF;
    private javax.swing.JTextField durationTF;
    private javax.swing.JTextField flightNumTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> otodComboBox;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTextField sourceTF;
    // End of variables declaration//GEN-END:variables
}
