/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PropertyCompany.leasing;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LeasingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SignLeaseRequest;
import Business.property.Lease;
import Business.property.Rent;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class RenewalRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form customerServiceJPanel
     */
     JPanel userProcessContainer;
    UserAccount ua;
    EcoSystem ecosystem;
    LeasingOrganization leaseOrganization;
    Enterprise enterprise;
    SignLeaseRequest slr;
   
    public RenewalRequestJPanel(JPanel userProcessContainer, UserAccount account, LeasingOrganization leaseOrganization, Enterprise enterprise, EcoSystem business, 
            SignLeaseRequest slr
    ) {
         initComponents();
         this. userProcessContainer = userProcessContainer;
         this.ua = account;
         this.leaseOrganization = leaseOrganization;
         this.enterprise = enterprise ;
         this.ecosystem=business;
         this.slr = slr ;
         populateTextField();
    }

       public  String dateToString(Date date){
         DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");  
         String strDate = dateFormat.format(date);  
         return strDate ;
   }
  
    public  Date getNextMonth(Date date){
          Calendar cal=Calendar.getInstance();
          cal.setTime(date);
          cal.set(Calendar.MONTH, date.getMonth()+1);
          Date dueDate = new Date(cal.getTimeInMillis());
         return dueDate ;
     } //    
       
   private void populateTextField(){
            Lease lease =  this.slr.getLease() ;
            Date startDate = getNextMonth(lease.getEndDate()) ;
            // EndDate
             Calendar cal=Calendar.getInstance();
            cal.setTime(startDate);
            cal.set(Calendar.MONTH,startDate.getMonth()+2);
            Date leaseEndDate =  cal.getTime() ;
            txtStartDate.setText(this.dateToString(startDate));
            
            txtEndDate.setText(this.dateToString(leaseEndDate));
            txtRentalDate.setText(this.dateToString(startDate));
                
            if( lease.getBalance() != null )
                txtBalance.setText(String.valueOf(lease.getBalance()));
            txtSecurityDeposit.setText(String.valueOf(0.0));
            txtBuilding.setText(lease.getBuilding().toString());
            txtTenant.setText(lease.getTenant().getUsername());
            if( lease.getTermination() != null )
                txtTerminationDate.setText(dateToString(lease.getTermination().getLeavingDate()));
            else
                txtTerminationDate.setText("No Termination");                     
        
   }//
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnSubmitRenwalRequest = new javax.swing.JButton();
        txtStartDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRentalDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSecurityDeposit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBuilding = new javax.swing.JTextField();
        txtTenant = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTerminationDate = new javax.swing.JTextField();
        backJButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setLayout(null);

        jLabel5.setText("Lease Detail");
        add(jLabel5);
        jLabel5.setBounds(360, 30, 159, 22);

        btnSubmitRenwalRequest.setText("Submit Renwal Request");
        btnSubmitRenwalRequest.setToolTipText("");
        btnSubmitRenwalRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRenwalRequestActionPerformed(evt);
            }
        });
        add(btnSubmitRenwalRequest);
        btnSubmitRenwalRequest.setBounds(600, 220, 190, 70);

        txtStartDate.setEnabled(false);
        add(txtStartDate);
        txtStartDate.setBounds(470, 90, 80, 20);

        jLabel1.setText("Start Date");
        add(jLabel1);
        jLabel1.setBounds(310, 90, 50, 14);

        jLabel3.setText("End Date");
        add(jLabel3);
        jLabel3.setBounds(310, 130, 44, 14);

        txtEndDate.setEnabled(false);
        add(txtEndDate);
        txtEndDate.setBounds(470, 130, 80, 20);

        jLabel4.setText("Rental Date");
        add(jLabel4);
        jLabel4.setBounds(310, 180, 57, 14);

        txtRentalDate.setEnabled(false);
        add(txtRentalDate);
        txtRentalDate.setBounds(470, 170, 80, 20);

        jLabel6.setText("Balance");
        add(jLabel6);
        jLabel6.setBounds(310, 220, 37, 14);

        txtBalance.setEnabled(false);
        add(txtBalance);
        txtBalance.setBounds(470, 210, 80, 20);

        jLabel7.setText("Security Deposit");
        add(jLabel7);
        jLabel7.setBounds(310, 260, 78, 14);

        txtSecurityDeposit.setEnabled(false);
        add(txtSecurityDeposit);
        txtSecurityDeposit.setBounds(470, 260, 80, 20);

        jLabel8.setText("Building");
        add(jLabel8);
        jLabel8.setBounds(310, 310, 36, 14);

        txtBuilding.setEnabled(false);
        add(txtBuilding);
        txtBuilding.setBounds(470, 300, 80, 20);

        txtTenant.setEnabled(false);
        add(txtTenant);
        txtTenant.setBounds(470, 350, 80, 20);

        jLabel9.setText("Tenant");
        add(jLabel9);
        jLabel9.setBounds(310, 350, 34, 14);

        jLabel10.setText("Termination Date");
        add(jLabel10);
        jLabel10.setBounds(310, 400, 82, 14);

        txtTerminationDate.setEnabled(false);
        add(txtTerminationDate);
        txtTerminationDate.setBounds(470, 390, 80, 20);

        backJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back-arrow.png"))); // NOI18N
        backJButton2.setBorderPainted(false);
        backJButton2.setContentAreaFilled(false);
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });
        add(backJButton2);
        backJButton2.setBounds(80, 50, 60, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel11.setText("jLabel4");
        add(jLabel11);
        jLabel11.setBounds(0, 0, 930, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitRenwalRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRenwalRequestActionPerformed
        // TODO add your handling code here:
        this.slr.setStatus("Renewal Request");
        JOptionPane.showMessageDialog(null, "Submit Renewal Request to Tenant", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSubmitRenwalRequestActionPerformed

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed

        CardLayout layout =  (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new RenewalJPanel(userProcessContainer,  ua,  leaseOrganization,  enterprise, ecosystem));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton2;
    private javax.swing.JButton btnSubmitRenwalRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBuilding;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtRentalDate;
    private javax.swing.JTextField txtSecurityDeposit;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTenant;
    private javax.swing.JTextField txtTerminationDate;
    // End of variables declaration//GEN-END:variables
}
