/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PropertyCompany.cutomerSupport;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.RealEstateEnterprise;
import Business.Network.Network;
import Business.Organization.CustomerSupportOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CustomerSupportRequest;
import Business.WorkQueue.RepairRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.PropertyCompany.repair.ProcessJPanel;

/**
 *
 * @author Mchig
 */
public class CustomerSupportWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TenantWorkAreaJPanel
     */
    
  JPanel userProcessContainer;
    UserAccount ua;
    EcoSystem ecosystem;
    CustomerSupportOrganization CSO;
    public CustomerSupportWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,  CustomerSupportOrganization CustomerSupportOrganization, Enterprise enterprise, EcoSystem business) {
         initComponents();
         this.ecosystem=business;
         this.ua = account;
         this. userProcessContainer = userProcessContainer;
         this.CSO=getOrg();
         populateFeedbackTable();
    }
    public void populateFeedbackTable() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        if(CSO.getWorkQueue().getCustomerSupportRequestList()==null){
            return;
        }
        for (CustomerSupportRequest wq : CSO.getWorkQueue().getCustomerSupportRequestList()) {
            Object[] row = new Object[jTable2.getColumnCount()];
            row[0] = wq;
            row[1] = wq.getCustomerAccount();
            row[2] = wq.getAssistant();
            row[3] = wq.getUpdateDate();
            row[4] = wq.getStatus();
            model.addRow(row);
        }
    }
    
    CustomerSupportOrganization getOrg(){
        for(Network net: ecosystem.getNetworkList()){
            for(Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()){
                if (ent instanceof RealEstateEnterprise) {
                    for(Organization organization: ent.getOrganizationDirectory().getOrganizationList()){
                        if (organization instanceof CustomerSupportOrganization) {
                            return (CustomerSupportOrganization)organization;
                        }
                    }
                } 
            }
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-customer-support-50.png"))); // NOI18N
        jLabel1.setText("Customer Support");
        add(jLabel1);
        jLabel1.setBounds(290, 0, 310, 50);

        jButton1.setText("Process");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(406, 318, 280, 60);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title", "Customer", "Assistant", "Updated Date", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2);
        jScrollPane2.setBounds(8, 60, 880, 240);

        jButton2.setText("Asign me");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(138, 318, 250, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(5, -4, 930, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row","Warning",JOptionPane.ERROR_MESSAGE);
            return;
        }
        CustomerSupportRequest request = (CustomerSupportRequest)jTable2.getValueAt(selectedRow, 0);

        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new viewCusotmerSupportJPanel(userProcessContainer, ua, ecosystem,request));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"please select a row","Warning",JOptionPane.ERROR_MESSAGE);
            return;
        }
        CustomerSupportRequest request = (CustomerSupportRequest)jTable2.getValueAt(selectedRow, 0);
        request.setAssistant(ua);
        request.setStatus("Processing");
        request.setUpdateDate(new Date());
        populateFeedbackTable();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
