/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PropertyCompany.leasing;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LeasingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SignLeaseRequest;
import Business.property.Lease;
import Business.property.Rent;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class DetailLeaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form customerServiceJPanel
     */
    JPanel userProcessContainer;
    UserAccount ua;
    EcoSystem eco;
    LeasingOrganization  leaseOrganization ;
    Enterprise enterprise ;
    SignLeaseRequest slr;
    String prevInterface;
   
    public DetailLeaseJPanel(JPanel userProcessContainer, UserAccount account, LeasingOrganization leaseOrganization, Enterprise enterprise, EcoSystem business,
            SignLeaseRequest slr, String prevInterface) {
         initComponents();
         this. userProcessContainer = userProcessContainer;
         this.ua = account;
         this.leaseOrganization = leaseOrganization;
         this.enterprise = enterprise ;
         this.eco=business;
         this.slr = slr ;
         this.prevInterface = prevInterface ;
         populateTextField();
    }

     public  String dateToString(Date date){
         DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");  
         String strDate = dateFormat.format(date);  
         return strDate ;
   }
  
   private void populateTextField(){
            Lease lease =  this.slr.getLease() ;
            txtStartDate.setText(this.dateToString(lease.getStartDate()));
            
            txtEndDate.setText(this.dateToString(lease.getEndDate()));
            if(  this.slr.getLease().getRentList().size() == 0 ){
                txtRentalDate.setText(this.dateToString(lease.getRentalDate()));
            }//
            else{
                ArrayList<Rent> rents = this.slr.getLease().getRentList();
                Rent currentRent = rents.get(rents.size()-1);
                txtRentalDate.setText(this.dateToString(currentRent.getDate()) );
            }
                
            if( lease.getBalance() != null )
                txtBalance.setText(String.valueOf(lease.getBalance()));
            txtSecurityDeposit.setText(String.valueOf(lease.getSecurityDeposit()));
            txtBuilding.setText(lease.getBuilding().toString());
            txtTenant.setText(lease.getTenant().getUsername());
            if( lease.getTermination() != null )
                txtTerminationDate.setText(dateToString(lease.getTermination().getLeavingDate()));
            else
                txtTerminationDate.setText("No Termination");
            
            // populate rental list
           if( lease.getRentList().size() != 0 ){
                RentsCombobox.removeAllItems();
                ArrayList<Rent> rentList = lease.getRentList() ;
                for (Rent r : rentList ) {
                    RentsCombobox.addItem(r);
                }
           }//
           else{
               RentsCombobox.removeAllItems();
               RentsCombobox.addItem("No Payment");
           }
               
           
   }//
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        RentDetailJButton = new javax.swing.JButton();
        txtStartDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRentalDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSecurityDeposit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBuilding = new javax.swing.JTextField();
        txtTenant = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTerminationDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        RentsCombobox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setLayout(null);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Lease Detail");
        add(jLabel5);
        jLabel5.setBounds(390, 40, 159, 22);

        RentDetailJButton.setText("View Alll Rents Details");
        RentDetailJButton.setToolTipText("");
        RentDetailJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentDetailJButtonActionPerformed(evt);
            }
        });
        add(RentDetailJButton);
        RentDetailJButton.setBounds(600, 280, 190, 70);

        txtStartDate.setEnabled(false);
        add(txtStartDate);
        txtStartDate.setBounds(460, 90, 80, 20);

        jLabel1.setText("Start Date");
        add(jLabel1);
        jLabel1.setBounds(330, 90, 90, 14);

        jLabel3.setText("End Date");
        add(jLabel3);
        jLabel3.setBounds(330, 130, 90, 14);

        txtEndDate.setEnabled(false);
        add(txtEndDate);
        txtEndDate.setBounds(460, 130, 80, 20);

        jLabel4.setText("Rental Date");
        add(jLabel4);
        jLabel4.setBounds(330, 180, 90, 14);

        txtRentalDate.setEnabled(false);
        add(txtRentalDate);
        txtRentalDate.setBounds(460, 180, 80, 20);

        jLabel6.setText("Balance");
        add(jLabel6);
        jLabel6.setBounds(330, 220, 80, 14);

        txtBalance.setEnabled(false);
        add(txtBalance);
        txtBalance.setBounds(460, 220, 80, 20);

        jLabel7.setText("Security Deposit");
        add(jLabel7);
        jLabel7.setBounds(330, 270, 120, 14);

        txtSecurityDeposit.setEnabled(false);
        add(txtSecurityDeposit);
        txtSecurityDeposit.setBounds(460, 260, 80, 20);

        jLabel8.setText("Building");
        add(jLabel8);
        jLabel8.setBounds(330, 310, 90, 14);

        txtBuilding.setEnabled(false);
        add(txtBuilding);
        txtBuilding.setBounds(460, 300, 80, 20);

        txtTenant.setEnabled(false);
        add(txtTenant);
        txtTenant.setBounds(460, 350, 80, 20);

        jLabel9.setText("Tenant");
        add(jLabel9);
        jLabel9.setBounds(330, 350, 80, 14);

        jLabel10.setText("Termination Date");
        add(jLabel10);
        jLabel10.setBounds(330, 390, 120, 14);

        txtTerminationDate.setEnabled(false);
        add(txtTerminationDate);
        txtTerminationDate.setBounds(460, 390, 80, 20);

        jLabel11.setText("Rent History");
        add(jLabel11);
        jLabel11.setBounds(330, 430, 90, 14);

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back-arrow.png"))); // NOI18N
        backJButton1.setBorderPainted(false);
        backJButton1.setContentAreaFilled(false);
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1);
        backJButton1.setBounds(150, 290, 60, 50);

        RentsCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(RentsCombobox);
        RentsCombobox.setBounds(460, 430, 140, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel12.setText("jLabel4");
        add(jLabel12);
        jLabel12.setBounds(5, -4, 930, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void RentDetailJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentDetailJButtonActionPerformed
        try{
             Rent selectedRent = (Rent)RentsCombobox.getSelectedItem();
            CardLayout layout =  (CardLayout)userProcessContainer.getLayout();
            userProcessContainer.add(new DetaiRentJPanel( userProcessContainer,  ua, leaseOrganization,  enterprise,  eco,
             slr,  selectedRent,  prevInterface) );
            layout.next(userProcessContainer);
        }
        catch( Exception e){
        }
    }//GEN-LAST:event_RentDetailJButtonActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        CardLayout layout =  (CardLayout)userProcessContainer.getLayout();
        if ( this.prevInterface.equals("ViewLease") ){
            userProcessContainer.add(new ViewLeaseJPanel(userProcessContainer,  ua,  leaseOrganization,  enterprise, eco));
        } // if
        else if(this.prevInterface.equals("Termination")){
            userProcessContainer.add(new TerminationJPanel(userProcessContainer,  ua,  leaseOrganization,  enterprise, eco));
        } // else if
        else if(this.prevInterface.equals("Renewal")){
            userProcessContainer.add(new RenewalJPanel(userProcessContainer,  ua,  leaseOrganization,  enterprise, eco));
        }      
        layout.next(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RentDetailJButton;
    private javax.swing.JComboBox<Object> RentsCombobox;
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBuilding;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtRentalDate;
    private javax.swing.JTextField txtSecurityDeposit;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTenant;
    private javax.swing.JTextField txtTerminationDate;
    // End of variables declaration//GEN-END:variables
}
